package com.sample
 
import com.sample.DroolsTest.Message;
 
 /*
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
*/

global javax.swing.JTable TB
global javax.swing.table.DefaultTableModel DFT


/***********Update Price*****************/
rule "Update Price"
	no-loop true
	salience 100 
	when
		$a: Armazem()
		$c: Cliente()
		$l: Loja()
		$i: Items($money : valor, $id : id)
		eval($a.getNumeroItems($id) > 0)
	then
		$l.addItemToCart($c, $i);
		update($l);
end
/***********Check Sex*****************/
rule "Check Item sex"
	//salience 100 
	when
		$a: Cliente()
		$b: Items($var : tipo)
		eval($a.checkMale($var))
	then
end

/***********Children*****************/
rule "Check Children" extends "Check Item sex"
	no-loop true
	salience 90 
	when
		$c: Cliente(children == true)
		$f: Armazem($lista : listItems)
		$i: Items(tipo == ($c.checkMaleString().equals("homem") ? "crianca_h" : "crianca_m")) from $lista
		eval($c.checkLastitem())
	then
		$c.deleteLastitem();
		for(int n = DFT.getRowCount()-1; n >= 0; n--){
			DFT.removeRow(n);
		}
		for(Items item : $f.getChildList($c.checkMaleString().equals("homem") ? "crianca_h" : "crianca_m")) {
			DFT.addRow(new Object[]{item.getId(), item.getImg(), item.getNome(), $f.getNumeroItems(item.getId()), item.getValor()});				
		}
		TB.setModel(DFT);
		
		update($c);
		retract($c);
end

/***********Married*****************/
rule "Check Married" extends "Check Item sex"
	salience 80
	when
		$c: Cliente(single == false)
		$f: Armazem($lista : listItems)
		$i: Items(tipo == ($c.checkMaleString().equals("homem") ? "mulher" : "homem"), descricao == $b.getDescricao()) from $lista
	then
		for(int n = DFT.getRowCount()-1; n >= 0; n--){
			DFT.removeRow(n);
		}
		for(Items item : $f.getDescriptionList(($c.checkMaleString().equals("homem") ? "mulher" : "homem"), $b.getDescricao())) {
			DFT.addRow(new Object[]{item.getId(), item.getImg(), item.getNome(), $f.getNumeroItems(item.getId()), item.getValor()});				
		}
		TB.setModel(DFT);
		retract($c);
end


/***********Single*****************/
rule "Check Single" extends"Check Item sex"
	salience 70
	when
		$c: Cliente(single == true, str : lastitem)
		$f: Armazem($lista : listItems)
		$i: Items(complementar == $b.getComplementar()) from $lista
		
	then
		for(int n = DFT.getRowCount()-1; n >= 0; n--){
			DFT.removeRow(n);
		}
		for(Items item : $f.getComplamentaryList($b.getComplementar())) {
			DFT.addRow(new Object[]{item.getId(), item.getImg(), item.getNome(), $f.getNumeroItems(item.getId()), item.getValor()});				
		}
		retract($c);
end

/**********Update Armazem**********/
rule "Check Armazem"
	salience 99
	when
		$a: Armazem($lista : listItems)
		$i: Items($a.getNumeroItems(id) < $a.getMinimumstock()) from $lista
	then
		$a.setMaxNumberItems($i.getId());
		update($a)
end
